import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.locator('div').filter({ hasText: /^Password$/ }).nth(2).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.locator('form i').first().click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('james lee');
  await page.locator('form i').nth(1).click();
  await page.getByRole('option', { name: 'Enabled' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('james');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('james1234');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('james1234');
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type for hints...' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type for hints...' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('jameslee');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('jameslee kool');
  await page.getByRole('button', { name: 'Save' }).click();
});